import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import {
  BookOpen,
  Search,
  Sparkles,
  Layers,
  Megaphone,
  Globe2,
  Users2,
  Calendar,
  Settings,
  ToyBrick,
  FileText,
  Copy,
  Check,
  ExternalLink,
  ChevronRight,
  ShieldCheck,
  Coins,
  ArrowRight,
  TrendingUp,
  Cpu,
  Terminal,
  HelpCircle,
  ThumbsUp,
  ThumbsDown
} from 'lucide-react';
import { Navbar } from '../components/Navbar';
import { Footer } from '../components/Footer';
import { GlowButton } from '../components/GlowButton';

interface ManualSection {
  id: string;
  title: string;
  icon: any;
  badge: string;
  badgeColor: string;
  steps: {
    title: string;
    description: string;
    codeSnippet?: string;
    tips?: string;
  }[];
}

export const UserManualsPage: React.FC = () => {
  const navigate = useNavigate();
  const [activeSectionId, setActiveSectionId] = useState<string>('getting-started');
  const [searchQuery, setSearchQuery] = useState('');
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);
  const [feedbackGiven, setFeedbackGiven] = useState<'up' | 'down' | null>(null);

  const handleCopyCode = (code: string, idx: number) => {
    navigator.clipboard.writeText(code);
    setCopiedIndex(idx);
    setTimeout(() => setCopiedIndex(null), 2000);
  };

  const manualSections: ManualSection[] = [
    {
      id: 'getting-started',
      title: '1. Getting Started & Brand Ingestion',
      icon: <Layers size={18} color="#7C75FF" />,
      badge: 'Core Setup',
      badgeColor: '#7C75FF',
      steps: [
        {
          title: 'Step 1: Enter your store or brand URL',
          description: 'On onboarding or within Knowledge Base > Brands, provide your official website (e.g. https://demobrand.com). Raftra’s autonomous crawler extracts logos, color hex codes, typography, product titles, and value propositions in under 30 seconds.',
          tips: 'Ensure your website has open graph meta tags for fastest asset extraction.'
        },
        {
          title: 'Step 2: Review Brand Kit extraction checklist',
          description: 'Verify extracted Brand Kit components: Logo, Colors, Typography, Knowledge Docs, Image Assets, and Target Market coordinates. Once confirmed, these serve as rigid design guardrails for all AI generators.',
          codeSnippet: `// Example Brand Coordinate Object generated by Raftra
{
  "brandName": "Demo Brand",
  "primaryColor": "#FF6B00",
  "accentColor": "#00E676",
  "typography": { "heading": "Outfit", "body": "Inter" },
  "keyUSPs": ["22.5W Fast Charging", "180-Day Warranty", "Made in India"]
}`
        },
        {
          title: 'Step 3: Multi-Brand Workspace Switching',
          description: 'Switch between multiple brand workspaces seamlessly from the top header switcher dropdown or under Settings > Brands.'
        }
      ]
    },
    {
      id: 'creative-studio',
      title: '2. AI Creative Studio Manual',
      icon: <Sparkles size={18} color="#00E676" />,
      badge: 'Ad Generation',
      badgeColor: '#00E676',
      steps: [
        {
          title: 'Generating 1:1 Static Feeds, 9:16 Stories & Carousels',
          description: 'Select your target aspect ratio and ad angle (e.g. Problem-Agitate-Solution, Social Proof, Flash Urgency, or Visual Demo). Click "Generate Creative" to produce high-CTR visual variants with pre-filled punchy headlines and call-to-actions.',
          tips: 'Use the live Canvas Editor to reposition headlines, overlays, badges, and export directly to Meta Ads Manager.'
        },
        {
          title: 'Producing 15s UGC Video Storyboards',
          description: 'Generate vertical video scripts with AI avatar voiceover prompts. Copy timestamped scripts or push video renders directly into your campaign queue.'
        }
      ]
    },
    {
      id: 'campaign-scaling',
      title: '3. Campaign Manager & ROAS Auto-Pilot',
      icon: <Megaphone size={18} color="#00D2FF" />,
      badge: 'Optimization',
      badgeColor: '#00D2FF',
      steps: [
        {
          title: 'Connecting Meta Ads & Google Ads Accounts',
          description: 'Navigate to Integrations and connect your Meta Business Manager and Google Ads accounts using OAuth 2.0 with read/write campaign execution permissions.',
          codeSnippet: `// Live Bid Scaling Guardrail Sample Rule
IF AdSet_ROAS > 3.8x AND Spend_Pacing < 85%
THEN Increase_Daily_Budget(+15%) EVERY 24h
MAX_BUDGET_CAP = ₹50,000 / day`
        },
        {
          title: 'Setting automated bid-scaling guardrails',
          description: 'Define minimum target ROAS thresholds. If an ad set exceeds target ROAS, Raftra automatically scales budget by 15% every 24h while pausing fatigued creatives.'
        }
      ]
    },
    {
      id: 'seo-aeo',
      title: '4. SEO & AEO Entity Indexing Engine',
      icon: <Globe2 size={18} color="#FFB300" />,
      badge: 'Search & AI',
      badgeColor: '#FFB300',
      steps: [
        {
          title: 'Publishing AI-optimized blog posts',
          description: 'Generate comprehensive, intent-focused articles with structured H1-H3 hierarchy, target keyword density, meta descriptions, and clean schema markup.',
          tips: 'Sync your CMS via Webhook or Shopify App for 1-click blog publishing.'
        },
        {
          title: 'Embedding JSON-LD schemas for ChatGPT & Perplexity',
          description: 'Ensure your product pages include rich JSON-LD Product entity schemas with verified customer review ratings, stock levels, and price attributes for generative search inclusion.'
        }
      ]
    },
    {
      id: 'influencer-vault',
      title: '5. Influencer Marketplace & Escrow Vault',
      icon: <Users2 size={18} color="#FF5296" />,
      badge: 'Creator Escrow',
      badgeColor: '#FF5296',
      steps: [
        {
          title: 'Filtering & shortlisting verified creators',
          description: 'Search through 5,000+ verified Indian creators by followers, engagement rate, average reel reach, and exact price rate cards (Reels, Stories, UGC videos).'
        },
        {
          title: 'Securing payments in Raftra Creator Escrow Vault',
          description: 'When finalizing a collaboration, funds are locked safely in escrow. Once the creator delivers the draft, completes review, and publishes the link, you approve and trigger immediate payout release.',
          tips: 'Use the official verification code copy tool to confirm deliverable satisfaction with the creator.'
        }
      ]
    },
    {
      id: 'reports-intelligence',
      title: '6. Market Trends & Competitor Intelligence',
      icon: <TrendingUp size={18} color="#7C75FF" />,
      badge: 'Ad Library',
      badgeColor: '#7C75FF',
      steps: [
        {
          title: 'Syncing Bi-Weekly Competitor Meta Ad Library Data',
          description: 'Click "Sync 2 Weeks Competitor Ads" to audit live active ads from Portronics, StuffCool, and niche competitors. Copy converting hooks or generate direct counter-creatives in Studio.',
          tips: 'This action is locked for 14 days after execution to ensure structured testing cycles.'
        },
        {
          title: 'Generating Monthly India Search Trend Radar',
          description: 'Click "Generate Monthly Report" to analyze 12-month keyword search trajectories, consumer intent shifts, and festive shopping spikes (Ganesh Chaturthi, Navratri, Diwali).'
        }
      ]
    },
    {
      id: 'plans-credits',
      title: '7. Plans, Indian Rupee Billing & Credits Hub',
      icon: <Coins size={18} color="#00E676" />,
      badge: '₹ INR Billing',
      badgeColor: '#00E676',
      steps: [
        {
          title: 'Understanding INR Pricing Tiers',
          description: 'Choose between Creator Launch (₹4,999/mo), D2C Growth Suite (₹8,999/mo), or Full Business Suite (₹19,999/mo). Switch to Annual billing to receive 2 Months FREE with full GST invoicing.',
          tips: 'Download PDF tax invoices directly from Settings > Plans & Billing.'
        },
        {
          title: 'Top-Up Execution Credits Balance',
          description: 'Execution credits are consumed for AI creative variants (50 credits), video storyboards (200 credits), and competitor scrapes (150 credits). Top up anytime from the top bar widget (+ ₹2,500, + ₹5,000, + ₹15,000).'
        }
      ]
    }
  ];

  const currentSection = manualSections.find(s => s.id === activeSectionId) || manualSections[0];

  const filteredSections = manualSections.filter(sec => {
    if (!searchQuery.trim()) return true;
    const q = searchQuery.toLowerCase();
    return sec.title.toLowerCase().includes(q) || sec.steps.some(s => s.title.toLowerCase().includes(q) || s.description.toLowerCase().includes(q));
  });

  return (
    <div style={{ minHeight: '100vh', background: '#050508', color: '#fff', display: 'flex', flexDirection: 'column' }}>
      <Navbar />

      <main style={{ flex: 1, maxWidth: '1280px', margin: '0 auto', padding: '120px 24px 80px 24px', width: '100%', boxSizing: 'border-box' }}>
        
        {/* ── HERO BANNER ────────────────────────────────────────── */}
        <div style={{ textAlign: 'center', maxWidth: '780px', margin: '0 auto 48px auto' }}>
          <div style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', padding: '5px 14px', background: 'rgba(0, 210, 255, 0.12)', borderRadius: '100px', border: '1px solid rgba(0, 210, 255, 0.3)', marginBottom: '16px' }}>
            <BookOpen size={14} color="#00D2FF" />
            <span style={{ fontSize: '12px', color: '#00D2FF', fontWeight: 800, letterSpacing: '0.04em', textTransform: 'uppercase' }}>
              OFFICIAL USER MANUALS & DOCUMENTATION
            </span>
          </div>

          <h1 style={{ fontSize: 'clamp(32px, 5vw, 48px)', color: '#fff', margin: '0 0 16px 0', fontWeight: 900, fontFamily: 'var(--font-heading)', lineHeight: 1.15 }}>
            Mastering the <span style={{ color: '#00E676' }}>Raftra AI Growth OS</span>
          </h1>

          <p style={{ fontSize: '16px', color: 'var(--text-secondary)', lineHeight: 1.6, margin: 0 }}>
            Comprehensive step-by-step guides, code samples, guardrail configurations, and best practices for scaling your brand.
          </p>

          {/* Large Search Bar */}
          <div style={{ marginTop: '28px', position: 'relative', maxWidth: '560px', margin: '28px auto 0 auto' }}>
            <Search size={18} color="var(--text-muted)" style={{ position: 'absolute', left: '18px', top: '50%', transform: 'translateY(-50%)' }} />
            <input
              type="text"
              placeholder="Search user manuals, features, API rules..."
              value={searchQuery}
              onChange={e => setSearchQuery(e.target.value)}
              style={{
                width: '100%',
                boxSizing: 'border-box',
                padding: '14px 20px 14px 48px',
                background: 'rgba(255, 255, 255, 0.04)',
                border: '1.5px solid rgba(0, 210, 255, 0.35)',
                borderRadius: '100px',
                color: '#fff',
                fontSize: '14.5px',
                outline: 'none',
                boxShadow: '0 8px 30px rgba(0, 210, 255, 0.12)'
              }}
            />
          </div>
        </div>

        {/* ── 2-COLUMN DOCUMENTATION LAYOUT ───────────────────────── */}
        <div className="manuals-main-grid">
          
          {/* LEFT SIDEBAR NAVIGATION */}
          <div className="manuals-sidebar glow-card">
            <div style={{ fontSize: '11px', fontWeight: 800, color: 'var(--text-muted)', padding: '8px 12px', textTransform: 'uppercase', letterSpacing: '0.04em' }}>
              DOCUMENTATION CHAPTERS
            </div>

            {filteredSections.map((sec) => {
              const isActive = sec.id === activeSectionId;
              return (
                <button
                  key={sec.id}
                  onClick={() => setActiveSectionId(sec.id)}
                  style={{
                    background: isActive ? 'rgba(0, 230, 118, 0.12)' : 'transparent',
                    border: '1px solid',
                    borderColor: isActive ? '#00E676' : 'transparent',
                    color: isActive ? '#00E676' : 'var(--text-secondary)',
                    padding: '10px 14px',
                    borderRadius: '12px',
                    fontSize: '13px',
                    fontWeight: isActive ? 700 : 500,
                    textAlign: 'left',
                    cursor: 'pointer',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'space-between',
                    gap: '10px',
                    transition: 'all 0.2s ease'
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', gap: '8px', overflow: 'hidden' }}>
                    {sec.icon}
                    <span style={{ textOverflow: 'ellipsis', whiteSpace: 'nowrap', overflow: 'hidden' }}>{sec.title}</span>
                  </div>
                  <ChevronRight size={13} style={{ opacity: isActive ? 1 : 0.4 }} />
                </button>
              );
            })}
          </div>

          {/* RIGHT CONTENT AREA */}
          <div
            className="glow-card"
            style={{
              background: '#0a0a12',
              border: '1px solid rgba(255, 255, 255, 0.08)',
              borderRadius: '24px',
              padding: '36px',
              display: 'flex',
              flexDirection: 'column',
              gap: '32px'
            }}
          >
            {/* Chapter Header */}
            <div style={{ borderBottom: '1px solid rgba(255,255,255,0.08)', paddingBottom: '20px', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '12px' }}>
              <div>
                <span style={{ fontSize: '11px', background: `${currentSection.badgeColor}22`, color: currentSection.badgeColor, border: `1px solid ${currentSection.badgeColor}55`, padding: '3px 10px', borderRadius: '100px', fontWeight: 800, textTransform: 'uppercase' }}>
                  {currentSection.badge}
                </span>
                <h2 style={{ fontSize: '26px', color: '#fff', margin: '10px 0 0 0', fontWeight: 900, fontFamily: 'var(--font-heading)' }}>
                  {currentSection.title}
                </h2>
              </div>

              <GlowButton
                variant="glow"
                onClick={() => navigate('/login')}
                style={{ fontSize: '12.5px', padding: '8px 20px' }}
              >
                Try in Dashboard 🚀
              </GlowButton>
            </div>

            {/* Steps Breakdown */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: '28px' }}>
              {currentSection.steps.map((step, idx) => (
                <div key={idx} style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                  <h3 style={{ fontSize: '17px', color: '#fff', margin: 0, fontWeight: 700, display: 'flex', alignItems: 'center', gap: '10px' }}>
                    <span style={{ width: '26px', height: '26px', borderRadius: '50%', background: 'rgba(255,255,255,0.06)', border: '1px solid rgba(255,255,255,0.15)', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', fontSize: '12px', fontWeight: 800, color: '#00E676' }}>
                      {idx + 1}
                    </span>
                    {step.title}
                  </h3>

                  <p style={{ fontSize: '14.5px', color: 'var(--text-secondary)', margin: 0, lineHeight: 1.6, paddingLeft: '36px' }}>
                    {step.description}
                  </p>

                  {/* Code Snippet Box (if available) */}
                  {step.codeSnippet && (
                    <div style={{ marginLeft: '36px', background: '#070709', border: '1px solid rgba(255,255,255,0.12)', borderRadius: '12px', padding: '16px', position: 'relative', overflowX: 'auto' }}>
                      <button
                        onClick={() => handleCopyCode(step.codeSnippet!, idx)}
                        style={{
                          position: 'absolute',
                          right: '12px',
                          top: '12px',
                          background: copiedIndex === idx ? 'rgba(0, 230, 118, 0.2)' : 'rgba(255, 255, 255, 0.08)',
                          border: '1px solid',
                          borderColor: copiedIndex === idx ? '#00E676' : 'rgba(255, 255, 255, 0.15)',
                          color: copiedIndex === idx ? '#00E676' : '#fff',
                          padding: '4px 10px',
                          borderRadius: '6px',
                          fontSize: '11px',
                          cursor: 'pointer',
                          display: 'flex',
                          alignItems: 'center',
                          gap: '4px'
                        }}
                      >
                        {copiedIndex === idx ? <Check size={11} /> : <Copy size={11} />}
                        <span>{copiedIndex === idx ? 'Copied' : 'Copy'}</span>
                      </button>

                      <pre style={{ margin: 0, fontFamily: 'var(--font-mono)', fontSize: '12.5px', color: '#00E676', lineHeight: 1.5 }}>
                        <code>{step.codeSnippet}</code>
                      </pre>
                    </div>
                  )}

                  {/* Tips Note */}
                  {step.tips && (
                    <div style={{ marginLeft: '36px', background: 'rgba(124, 117, 255, 0.08)', borderLeft: '3px solid #7C75FF', padding: '10px 14px', borderRadius: '0 8px 8px 0', fontSize: '13px', color: 'rgba(255,255,255,0.9)' }}>
                      <strong style={{ color: '#7C75FF' }}>Pro Tip:</strong> {step.tips}
                    </div>
                  )}
                </div>
              ))}
            </div>

            {/* Helpful Feedback Box */}
            <div style={{ borderTop: '1px solid rgba(255,255,255,0.08)', paddingTop: '20px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '14px' }}>
              <span style={{ fontSize: '13px', color: 'var(--text-secondary)' }}>
                Was this manual section helpful?
              </span>

              <div style={{ display: 'flex', gap: '8px' }}>
                <button
                  onClick={() => setFeedbackGiven('up')}
                  style={{
                    background: feedbackGiven === 'up' ? 'rgba(0, 230, 118, 0.2)' : 'rgba(255, 255, 255, 0.04)',
                    border: '1px solid',
                    borderColor: feedbackGiven === 'up' ? '#00E676' : 'rgba(255, 255, 255, 0.1)',
                    color: feedbackGiven === 'up' ? '#00E676' : '#fff',
                    padding: '6px 14px',
                    borderRadius: '100px',
                    fontSize: '12px',
                    fontWeight: 600,
                    cursor: 'pointer',
                    display: 'flex',
                    alignItems: 'center',
                    gap: '5px'
                  }}
                >
                  <ThumbsUp size={13} /> {feedbackGiven === 'up' ? 'Thank You!' : 'Yes, Helpful'}
                </button>

                <button
                  onClick={() => setFeedbackGiven('down')}
                  style={{
                    background: feedbackGiven === 'down' ? 'rgba(255, 71, 87, 0.2)' : 'rgba(255, 255, 255, 0.04)',
                    border: '1px solid',
                    borderColor: feedbackGiven === 'down' ? '#ff4757' : 'rgba(255, 255, 255, 0.1)',
                    color: feedbackGiven === 'down' ? '#ff4757' : '#fff',
                    padding: '6px 14px',
                    borderRadius: '100px',
                    fontSize: '12px',
                    fontWeight: 600,
                    cursor: 'pointer',
                    display: 'flex',
                    alignItems: 'center',
                    gap: '5px'
                  }}
                >
                  <ThumbsDown size={13} /> Need More Info
                </button>
              </div>
            </div>

          </div>

        </div>

      </main>

      <style>{`
        .manuals-main-grid {
          display: grid;
          grid-template-columns: 280px 1fr;
          gap: 28px;
          align-items: start;
        }
        .manuals-sidebar {
          background: #0a0a12;
          border: 1px solid rgba(255, 255, 255, 0.08);
          border-radius: 20px;
          padding: 16px;
          display: flex;
          flex-direction: column;
          gap: 6px;
          position: sticky;
          top: 90px;
        }

        @media (max-width: 960px) {
          .manuals-main-grid {
            grid-template-columns: 1fr !important;
            gap: 20px !important;
          }
          .manuals-sidebar {
            position: static !important;
            display: flex !important;
            flex-direction: row !important;
            overflow-x: auto !important;
            padding: 10px !important;
            white-space: nowrap !important;
            gap: 8px !important;
          }
          .manuals-sidebar > div {
            display: none !important;
          }
          .manuals-sidebar button {
            flex-shrink: 0 !important;
          }
        }
      `}</style>

      <Footer />
    </div>
  );
};
