"""add billing columns

Revision ID: 8b30e0556f18
Revises: 5d05375a853b
Create Date: 2026-07-05 16:01:33.187859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b30e0556f18'
down_revision: Union[str, Sequence[str], None] = '5d05375a853b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('billing_balance', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('unlocked_nodes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'unlocked_nodes')
    op.drop_column('users', 'billing_balance')
    # ### end Alembic commands ###
